export * from '../Shared/Interfaces/IWindowManager';
export * from '../Shared/Interfaces/IFileSystem';
export * from '../Shared/Interfaces/IThemeProvider';
export * from './UseCases/OpenWindow/OpenWindow';
export * from './UseCases/CloseWindow/CloseWindow';
export * from './UseCases/MinimizeWindow/MinimizeWindow';
export * from './UseCases/MoveWindow/MoveWindow';
export * from './UseCases/ResizeWindow/ResizeWindow';
export * from './UseCases/CreateDesktopIcon/CreateDesktopIcon';
