export * from './Ports/IWindowManager';
export * from './Ports/IFileSystem';
export * from './Ports/IThemeProvider';
export * from './UseCases/OpenWindow/OpenWindow';
export * from './UseCases/CloseWindow/CloseWindow';
export * from './UseCases/MinimizeWindow/MinimizeWindow';
export * from './UseCases/MoveWindow/MoveWindow';
export * from './UseCases/ResizeWindow/ResizeWindow';
export * from './UseCases/CreateDesktopIcon/CreateDesktopIcon';
